# Generated by Django 4.2.7 on 2024-01-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_ator', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('verb', models.CharField(default='postagem', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
